/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_yxh_jni_Test */

#ifndef _Included_com_yxh_jni_Test
#define _Included_com_yxh_jni_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yxh_jni_Test
 * Method:    callC
 * Signature: ([B[Ljava/lang/Object;[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_yxh_jni_Test_callC
  (JNIEnv *, jobject, jbyteArray, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
